python3 template.py 50 10 relu mean_squared_error SGD 
python3 template.py 50 10 relu mean_squared_error Adagrad 
python3 template.py 50 10 relu mean_squared_error Adadelta 
python3 template.py 50 10 relu mean_squared_logarithmic_error SGD 
python3 template.py 50 10 relu mean_squared_logarithmic_error Adagrad 
python3 template.py 50 10 relu mean_squared_logarithmic_error Adadelta 
python3 template.py 50 10 relu logcosh SGD 
python3 template.py 50 10 relu logcosh Adagrad 
python3 template.py 50 10 relu logcosh Adadelta 
